python3 main.py -f st_area -n 10_3
python3 main.py -f st_astext -n 10_3
python3 main.py -f st_envelope_aggr -n 10_3
python3 main.py -f st_envelope -n 10_3
python3 main.py -f st_union_aggr -n 10_3
python3 main.py -f st_issimple -n 10_3
python3 main.py -f st_transform -n 10_3
python3 main.py -f st_buffer -n 10_3
python3 main.py -f st_length -n 10_3
python3 main.py -f st_isvalid -n 10_3
python3 main.py -f st_npoints -n 10_3
python3 main.py -f st_centroid -n 10_3
python3 main.py -f st_convexhull -n 10_3
python3 main.py -f st_geometry_type -n 10_3
python3 main.py -f st_simplify_preserve_topology -n 10_3
python3 main.py -f st_make_valid -n 10_3
python3 main.py -f st_intersection -n 10_3
python3 main.py -f st_intersects -n 10_3
python3 main.py -f st_overlaps -n 10_3
python3 main.py -f st_contains -n 10_3
python3 main.py -f st_equals -n 10_3
python3 main.py -f st_crosses -n 10_3
python3 main.py -f st_touches -n 10_3
python3 main.py -f st_hausdorffdistance -n 10_3
python3 main.py -f st_distance -n 10_3
python3 main.py -f st_within -n 10_3
python3 main.py -f st_curvetoline -n 10_3
python3 main.py -f st_point -n 10_3
python3 main.py -f st_polygon_from_envelope -n 10_3
python3 main.py -f st_geomfromgeojson -n 10_3
